upload:
  enabled: true
  requireAuth: false

storage:
  backend: local
  rules:
    - type: "image/*"
      expiration: 1 month
    - type: "application/json"
      expiration: 1 month
    - type: "*"
      expiration: 1 week

dashboard:
  enabled: true
