version: "3.7"
services:
  blossom:
    image: ghcr.io/hzrd149/blossom-server:master
    ports:
      - 3000:3000
    volumes:
      - blossom-data:/app/data
      - ./blossom-config.yml:/app/config.yml
volumes:
  blossom-data: {}
