/**
 * Auto-generated by @contextvm/ctxcn
 *
 * CVM Server: Spryte CVM
 * Pubkey: <set after deployment>
 *
 * Regenerate with: npx ctxcn update
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import type { Transport } from "@modelcontextprotocol/sdk/shared/transport.js";
import {
  NostrClientTransport,
  type NostrTransportOptions,
  PrivateKeySigner,
  ApplesauceRelayPool,
} from "@contextvm/sdk";

// --- Generated Types ---

export type GenerateSpryteInput = {
  /** Hex-encoded Nostr pubkey to generate sprite for */
  pubkey: string;
  /** Pixel dimension for each cell (default: 128) */
  cellSize?: number;
  /** Blossom server URL for uploads (uses default if omitted) */
  uploadServer?: string;
};

export type GenerateSpryteOutput = {
  spriteUrl: string;
  mappingUrl: string;
  pubkeyCount: number;
  cellSize: number;
};

// --- Server Interface ---

export type SpryteCvm = {
  generateSpryte: (
    pubkey: string,
    cellSize?: number,
    uploadServer?: string,
  ) => Promise<GenerateSpryteOutput>;
};

// --- Client Class ---

export class SpryteCvmClient implements SpryteCvm {
  static readonly SERVER_PUBKEY = "";
  static readonly DEFAULT_RELAYS = ["wss://relay.damus.io"];

  private client: Client;
  private transport: Transport;

  constructor(
    options: Partial<NostrTransportOptions> & {
      privateKey?: string;
      relays?: string[];
      serverPubkey?: string;
    } = {},
  ) {
    const privateKey =
      options.privateKey ??
      (typeof process !== "undefined"
        ? process.env?.CTXCN_PRIVATE_KEY
        : undefined) ??
      "";

    const relays = options.relays ?? SpryteCvmClient.DEFAULT_RELAYS;
    const serverPubkey =
      options.serverPubkey ?? SpryteCvmClient.SERVER_PUBKEY;

    if (!serverPubkey) {
      throw new Error(
        "SpryteCvmClient: serverPubkey is required. Pass it in options or set SERVER_PUBKEY.",
      );
    }

    const signer = new PrivateKeySigner(privateKey);
    const relayPool = new ApplesauceRelayPool(relays);

    this.transport = new NostrClientTransport({
      ...options,
      signer,
      relayHandler: relayPool,
      serverPubkey,
      isStateless: true,
    });

    this.client = new Client({
      name: "spryte-client",
      version: "0.1.0",
    });
  }

  async connect(): Promise<void> {
    await this.client.connect(this.transport);
  }

  async disconnect(): Promise<void> {
    await this.client.close();
  }

  private async call<T = unknown>(
    name: string,
    args: Record<string, unknown>,
  ): Promise<T> {
    const result = await this.client.callTool({ name, arguments: { ...args } });

    // CVM returns text content with JSON; parse structuredContent or text
    if (result.structuredContent) {
      return result.structuredContent as T;
    }

    const content = result.content as Array<{ type: string; text: string }>;
    const textContent = content?.find((c) => c.type === "text");
    if (textContent) {
      return JSON.parse(textContent.text) as T;
    }

    throw new Error("Unexpected response format from CVM");
  }

  /**
   * Generate a sprite sheet of Nostr follower profile images for a given pubkey.
   * Returns URLs for the sprite PNG and mapping JSON on a Blossom server.
   *
   * @param pubkey - Hex-encoded Nostr pubkey to generate sprite for
   * @param cellSize - Pixel dimension for each cell (default: 128)
   * @param uploadServer - Blossom server URL for uploads (uses default if omitted)
   * @returns Sprite and mapping URLs with metadata
   */
  async generateSpryte(
    pubkey: string,
    cellSize?: number,
    uploadServer?: string,
  ): Promise<GenerateSpryteOutput> {
    const args: Record<string, unknown> = { pubkey };
    if (cellSize !== undefined) args.cellSize = cellSize;
    if (uploadServer !== undefined) args.uploadServer = uploadServer;
    return this.call<GenerateSpryteOutput>("generate-spryte", args);
  }
}
